Rc 14816
RafaySystems/terraform-provider-rafay pull request #115
Opened 2022-08-06 02:01 UTC by sougat-rafay

Completed proper handling of policy document field in eks cluster

2022-08-08 10:36 UTC, stephan-rafay requested changes

2022-08-08 10:36 UTC, stephan-rafay commented on examples/resources/rafay_eks_cluster/resource.tf
> +      cni_provider   = "regression-eks-role"
can you check cni_provider change?

2022-08-08 18:46 UTC, sougat-rafay reviewed
reverted changes from testing

2022-08-09 20:36 UTC, stephan-rafay approved these changes

2022-08-09 20:36 UTC, merged