OPA constraint document
RafaySystems/terraform-provider-rafay pull request #132
Opened 2022-09-08 22:25 UTC by darren-rafay

Updated the OPA Constraint file. Please review.

2022-09-09 02:34 UTC, stephan-rafay approved these changes

2022-09-09 03:01 UTC, hardik-rafay requested changes

2022-09-09 03:01 UTC, hardik-rafay commented on docs/resources/opa_constraint.md
> +- `wait` (Boolean) If enabled, deploy the resource with wait flag. This means wait until the deployment is in a ready state before marking the release as successful.
Remove all options.

2022-09-13 22:22 UTC, hardik-rafay approved these changes

2022-09-13 22:22 UTC, merged