Added AKS Cluster v3
RafaySystems/terraform-provider-rafay pull request #288
Opened 2023-05-05 19:52 UTC by darren-rafay

Added the AKS Cluster v3 topic to the Terraform Docs.

2023-05-27 05:38 UTC, mayank-rafay commented on docs/resources/aks_cluster_v3.md
> +        project = "defaultproject"
config.metadata.project field is incorrect. please remove it from the schema. We need to give the project details once which we provided in cluster metadata

2023-05-27 05:39 UTC, mayank-rafay commented on docs/resources/aks_cluster_v3.md
> +- `project` - (String) The name of the project in the Console.
remove project from here as well

2023-05-27 08:09 UTC, mayank-rafay approved these changes

2023-05-30 19:01 UTC, hardik-rafay requested changes

2023-05-31 17:33 UTC, hardik-rafay approved these changes

2023-05-31 17:34 UTC, merged