feat(GKE): add terraform support for dataplaneV2 & CalicoNetworkPolicy in clusterNetwork config
RafaySystems/terraform-provider-rafay pull request #554
Opened 2024-05-06 11:27 UTC by sharan-rafay

Jira: https://rafaysystems.atlassian.net/browse/RC-34510

2024-05-06 16:54 UTC, poornima-rafay approved these changes

2024-05-08 08:41 UTC, akshay196-rafay requested changes

2024-05-08 08:41 UTC, akshay196-rafay commented on docs/resources/gke_cluster.md
> +- `data_plane_V2` (String) Dataplane V2 is optimized for Kubernetes networking which is implemented using eBPF.
List supported values.

2024-05-08 08:41 UTC, akshay196-rafay commented on docs/resources/gke_cluster.md
> +- `calico_network_policy` (String) The Kubernetes Network Policy API allows the cluster administrator to specify what pods are allowed to communicate with each other. Cannot use with `data_plane_V2`
List supported values.

2024-05-08 12:10 UTC, sharan-rafay commented on docs/resources/gke_cluster.md
> +- `calico_network_policy` (String) The Kubernetes Network Policy API allows the cluster administrator to specify what pods are allowed to communicate with each other. Cannot use with `data_plane_V2`
updated.

2024-05-08 12:10 UTC, sharan-rafay commented on docs/resources/gke_cluster.md
> +- `data_plane_V2` (String) Dataplane V2 is optimized for Kubernetes networking which is implemented using eBPF.
updated

2024-05-14 13:09 UTC, akshay196-rafay approved these changes

2024-05-26 04:13 UTC, merged